# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20161213_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='base_url',
        ),
        migrations.AddField(
            model_name='app',
            name='base_URL',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='base_URL',
            field=models.CharField(default='foo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourceaction',
            name='name',
            field=models.CharField(default='foo', max_length=255),
            preserve_default=False,
        ),
    ]
