# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20161213_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='base_URL',
            new_name='base_url',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='base_URL',
            new_name='base_url',
        ),
    ]
